name: Update News

on:
  workflow_dispatch:
  schedule:
    # كل 10 دقائق (قد يتأخر التنفيذ قليلاً حسب GitHub)
    - cron: "*/10 * * * *"

permissions:
  contents: write

concurrency:
  group: update-news
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
      # مهم: fetch-depth صفر عشان نعرف نعمل rebase قبل الـ push
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            scripts/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Fetch & summarise news
        run: |
          python scripts/update_news.py
        env:
          PYTHONWARNINGS: ignore

      - name: Commit updated news.json
        run: |
          # لو مفيش تغييرات لا تعمل شيء
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name  "news-bot"
          git config user.email "bot@users.noreply.github.com"

          git add news.json
          git commit -m "Update news feed [skip ci]"

          # اسحب أي تغييرات بعيدة ثم ادفع
          # مع rebase لتفادي "rejected (fetch first)"
          git pull --rebase origin "${GITHUB_REF_NAME:-main}" || true
          git push origin HEAD:"${GITHUB_REF_NAME:-main}" --force-with-lease
