name: Update News
on:
  schedule:
    - cron: '*/5 * * * *'  # تشغيل كل 5 دقائق
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser beautifulsoup4 transformers
      
      - name: Fetch and summarise news
        run: python scripts/update_news.py

      - name: Commit updated news.json
        run: |
          git config --local user.email "bot@example.com"
          git config --local user.name "News Bot"
          git add news.json
          git commit -m "Update news feed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
